io:
  logdir: logs/
  datadir: data/wireframe/
  resume_from:
  num_workers: 4
  tensorboard_port: 0
  validation_interval: 24000

model:
  image:
      mean: [109.730, 103.832, 98.681] # not mean & stddev of current dataset
      stddev: [22.275, 22.124, 23.229]

  batch_size: 6
  batch_size_eval: 2

  # backbone multi-task parameters
  head_size: [[2], [2], [2], [2]] #center,corner,corner_offset,corner_bin_offset
  loss_weight:
    center: 1 #0.5
    corner: 1 #8.0
    corner_offset: 5
    corner_bin_offset: 1 #0.25

  # backbone parameters
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 2
  num_blocks: 1

  # maximum junction and line outputs
  n_out_junc: 250
  n_out_line: 2500

  # additional ablation study parameters
  use_cood: 0
  use_slop: 0
  use_conv: 0

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.008

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 1.0e-4
  max_epoch: 24
  lr_decay_epoch: 10
